---
cloud_service_group: Compliance
cloud_service_type: EventLogging
name: Failed Count
query:
  aggregate:
    - count:
        name: value
  filter:
    - key: data.status
      value: FAILED
      operator: eq
options:
  value_options:
    key: value
    options:
      default: 0